export const COURSE_LIST_REQUEST='COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS='COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL='COURSE_LIST_FAIL';

export const COURSE_DETAILS_REQUEST='COURSE_DETAILS_REQUEST';
export const COURSE_DETAILS_SUCCESS='COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL='COURSE_DETAILS_FAIL';

export const COURSE_UPLOAD_REQUEST='COURSE_UPLOAD_REQUEST';
export const COURSE_UPLOAD_SUCCESS='COURSE_UPLOAD_SUCCESS';
export const COURSE_UPLOAD_FAIL='COURSE_UPLOAD_FAIL';
export const COURSE_UPLOAD_RESET='COURSE_UPLOAD_RESET';




